### PR TITLE
Changed functions signature to prevent naming clash

### PR DESCRIPTION
**Pull request by Prev-I**
I've managed to change all function names so I can use them without clash problem with base::get and base::merge functions.

I'm aware that this changes break the package usage, but I thought it was a change worth sharing with upstream. Even in R studio using this package is problematic in loaded inside an .rprofile 

I've also found a little bug in directory navigation under Linux and R 3.3. The fixes is included in this pull request. If you prefer I can commit that separately

### CODE REVIEW

**Comment by jjallaire** [comment]
You are correct that I can't really change the name of `get` at this point b/c it will break lots and lots of user code. The idea is that you will never call these functions via `library(config)` but rather will use:

```r
config <- config::get()
```

**Comment by Prev-I** [comment]
the problem arise when somewhere get or merge is called without specifying base package (And here where I work it happens a lot). 

Even in Rstudio if you have the following .Rprofile when starting a project:
```
.First <- function(){
library("config")
config <- config::get()
}
```
Rstudio crash hard and refuse to start...

**Comment by jjallaire** [comment]
The idea is that you never call library(config), you always call the
function via ::

**Comment by Prev-I** [comment]
you are right, but given that the other way of calling is still valid R code make usage error prone, at least in my experience.

Anyway given the amount of changes probably is a wise choice to keep it as is

**Comment by jjallaire** [comment]
Okay, I agree that if I had to do it all over again I wouldn't name it get.
My hope was that if we documented config::get that no one would run into
this trouble.

**Comment by landroni** [comment]
@jjallaire 

I must admit I got confused about the correct usage of `config` (i.e. NOT do `library(config)`). For instance, this isn't explicitly mentioned in the README. I would suggest adding a note to this effect, as the naming choice makes one think twice before deciding to use the package.

**Comment by jjallaire** [comment]
Okay, I just added some notes to the documentation to clarify this.

**Comment by DougManuel** [comment]
What about  not replacing  `get` with `get_config` but adding `get_config`? That would not break legacy code. 

`config::get()` would have the same behaviour as `get_config()`

**Comment by jjallaire** [comment]
Adding `get_config()` as an alternative is a good idea, but it still won't really allow you to do `library(config)` without masking `base::get`.

**Comment by DougManuel** [comment]
Maybe we just need to get more comfortable with `::` in the R community. 

It is a helpful explicit practice that we use in other open languages. Name conflicts and masking will increase over time as the number of packages increase.

**Comment by andrie** [comment]
Closing this topic.  The preferred usage is to explicitly call `config::get()`

**Pull request closed without merging**
